catenax-ng/tx-portal-frontend

cx-portal-shared-components/src/components/basic/ToolTips/ToolTips.stories.tsx
cx-portal-shared-components/src/components/basic/ToolTips/index.tsx

* Add light color theme to Tooltip
* Simplify Tooltip component

CPLP-1876: Tooltip design

---

cx-portal/src/assets/locales/de/main.json
cx-portal/src/assets/locales/en/main.json

IdP locales, style & help

---

cx-portal/src/assets/locales/de/main.json
cx-portal/src/assets/locales/en/main.json
cx-portal/src/components/pages/DigitalTwins/TwinTable.tsx
cx-portal/src/components/pages/InviteBusinessPartner/components/InviteList/index.tsx
cx-portal/src/components/pages/NotificationCenter/index.tsx
cx-portal/src/components/pages/PartnerNetwork/index.tsx
cx-portal/src/components/pages/SemanticHub/ModelTable.tsx
cx-portal/src/components/shared/basic/LoadMoreButton/index.tsx

This is the follow-up to #13. It integrates the new Load More button into the portal so that the new button is used in all existing places.

CPLP-1875: Integrate Load More button into portal

---

cx-portal/src/components/pages/DigitalTwins/TwinTable.tsx
cx-portal/src/components/pages/NotificationCenter/index.tsx
cx-portal/src/components/pages/SemanticHub/ModelTable.tsx

fix linter issues

---

cx-portal-shared-components/src/components/basic/Dialog/Dialog.stories.tsx
cx-portal-shared-components/src/components/basic/Dialog/DialogActions.tsx
cx-portal-shared-components/src/components/basic/Dialog/DialogContent.tsx
cx-portal-shared-components/src/components/basic/Dialog/DialogHeader.tsx
cx-portal-shared-components/src/components/basic/Dialog/index.tsx
cx-portal-shared-components/src/components/basic/Table/PageLoadingTable.tsx
cx-portal-shared-components/src/theme.ts
cx-portal/src/components/pages/ServiceMarketplace/RecommendedServices.tsx
cx-portal/src/components/pages/ServiceMarketplace/index.tsx

* Refactor modal dialog default width
* Add better integration for MUI maxWidth and fullWidth settings
* Expand Storybook story
* Center text content by default

CPLP-1587: Modal dialog adjustments

---

CHANGELOG.md
cx-portal/src/components/pages/AppOverview/AppOverViewDetails.tsx
cx-portal/src/components/pages/AppReleaseProcess/components/AppMarketCard/index.tsx
cx-portal/src/components/pages/AppReleaseProcess/components/ValidateAndPublish/index.tsx
cx-portal/src/features/appManagement/apiSlice.ts
cx-portal/src/features/appManagement/types.ts

Reverts catenax-ng/tx-portal-frontend#33
@lavanya-bmw this PR breaks the build because there are linter issues - so we revert it for now. I have restored the branch to fix the issues and raise PR again

Revert "Business Logic & API: Document Endpoint Get and PUT PNG/JPEG"

---

CHANGELOG.md
cx-portal/src/assets/locales/de/main.json
cx-portal/src/assets/locales/en/main.json
cx-portal/src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorInsertForm.tsx
cx-portal/src/components/pages/EdcConnector/AddConnectorOverlay/index.tsx
cx-portal/src/components/pages/EdcConnector/EdcConnector.scss
cx-portal/src/components/pages/EdcConnector/edcConnectorTableColumns.tsx
cx-portal/src/components/pages/EdcConnector/index.tsx
cx-portal/src/components/shared/frame/PictureWithText/PictureWithText.scss
cx-portal/src/components/shared/frame/PictureWithText/index.tsx

Reverts catenax-ng/tx-portal-frontend#66

Revert "Dropzone title added"

---

cx-portal-shared-components/package.json
cx-portal/package.json
package.json

https://jira.catena-x.net/browse/CPLP-1864

cplp-1864: bump version for release of v1.0.0-RC1

---

.github/workflows/checks.yml

run linter checks not only on build but on every pr

add linter checks on pr

---

DEPENDENCIES
cx-portal-shared-components/package.json
cx-portal/package.json
package.json

https://jira.catena-x.net/browse/CPLP-1864

cplp-1864: bump version and update dependencies file for release of v1.0.0-RC3

---

cx-portal/public/index.html
cx-portal/src/services/EnvironmentService.ts
scripts/inject-dynamic-env.sh

https://jira.catena-x.net/browse/CPLP-1874

cplp-1874: change portal frontend to portal assets

---

cx-portal/src/components/MainOverlay.tsx
cx-portal/src/components/pages/NotificationCenter/NotificationItem.tsx
cx-portal/src/components/pages/NotificationCenter/index.tsx
cx-portal/src/features/notification/types.ts

Min Height set in notification section to prevent displace of footer on each load

Style fixes

---

.conf/Dockerfile.full
.conf/Dockerfile.prebuilt
.github/workflows/veracode.yaml
package.json
yarn.lock

fix dependabot findings: add selective dependency resolutions
add temp fix for cve-2023-0286 - https://jira.catena-x.net/browse/CPLP-1906

fix: resolve dependabot findings and temp fix for cve-2023-0286

---

CHANGELOG.md
cx-portal/src/components/pages/AppReleaseProcess/components/AppMarketCard/index.tsx
cx-portal/src/components/pages/AppReleaseProcess/components/ValidateAndPublish/index.tsx
cx-portal/src/features/appManagement/apiSlice.ts
cx-portal/src/features/appManagement/types.ts
cx-portal/src/services/CommonService.ts

Ticket CPLP-2118 & first implementation of CPLP-1889

Added new attribute provacyPolicies to app creation

---

CHANGELOG.md
cx-portal/src/components/pages/Admin/components/RegistrationRequests/components/CheckList/CheckListStatusOverlay.tsx
cx-portal/src/components/pages/Admin/components/RegistrationRequests/components/RequestList/index.tsx
cx-portal/src/features/admin/applicationRequestApiSlice.ts
cx-portal/src/features/admin/registration/actions.ts
cx-portal/src/features/admin/registration/slice.ts

Approve/Decline/Retrigger/Cancel Process actions should clear button and update the latest status in both overlay and application list

Checklist status sync issue - CPLP2247

---

.github/workflows/build.yml
.github/workflows/kics.yml
.github/workflows/trivy-dev.yml
.github/workflows/trivy-stable.yml

run kics scan on dev
limit build workflow to dev
introduce separate trivy scan for dev

chore(enable_multi_branch): update workflows

---

.conf/Dockerfile.full
.conf/Dockerfile.prebuilt

- add temp fix for CVE-2023-23916
- remove obsolete temp fix for CVE-2023-0286

fix(cve-2023-23916): add package upgrade as temp fix

---

.github/workflows/release.yml

follow up to https://github.com/catenax-ng/tx-portal-frontend/pull/230

chore(enable_multi_branch): add latest tag to released images

---

CHANGELOG.md
DEPENDENCIES
NOTICE.md
cx-portal-shared-components/package.json
cx-portal/package.json
package.json

release v1.1.0: merge main in dev

---

.tractusx
package.json
yarn.lock

fix(dependabot-alert): upgrade webpack via resolution
ref: CPLP-2362
chore(trg): add repo metafile
ref: CPLP-2334
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5

chore: fix dependabot alert and add repo metafile

---

package.json
yarn.lock

- fix(dependabot-alert): upgrade specifically webpack5 via resolution
ref: CPLP-2362

fix(dependabot-alert): upgrade webpack5 via resolution

---

package.json

fix(veracode-SCA): provide yarn.lock on project level
ref: CPLP-2249

fix(veracode-SCA): provide yarn.lock on project level

---

cx-portal/src/types/Patterns.ts

allow any character for client secret and restrict length to 1-200 chars

bugfix / CPLP-2312 / enhance idp client secret character set

---

CHANGELOG.md
DEPENDENCIES
cx-portal-shared-components/package.json
cx-portal/package.json
package.json

release(1.2.0): resolve conflicts

---

.conf/Dockerfile.full
.conf/Dockerfile.prebuilt
.github/workflows/build.yml
.github/workflows/kics.yml
.github/workflows/release-candidate.yml
.github/workflows/release.yml

- fix(cve-2023-0464): add temp fix
ref: CPLP-2456
- chore(workflows): update actions
- chore(workflows): direct dispatch to renamed workflow file
- build(env): add build workflow for v1.3.0 release candidate phase
ref: CPLP-2330

chore(enabler): actions+security upgrades and add build workflow for v1.3.0

---

cx-portal/src/types/Patterns.test.ts
cx-portal/src/types/Patterns.ts

User's first and last name field will accept 2 words.
Ex - Mano Dev
and more restrictions added to the string

Bugfix. Pattern update : Pattern to validate user's first and last name has been updated

---

cx-portal/src/components/pages/ServiceMarketplaceDetail/components/MarketplaceDocuments/index.tsx

user service document end point instead of app in Service details page(Service Marketplace section)

BugFix. End point Update : fetch serviceDocument

---

CHANGELOG.md
cx-portal/src/assets/locales/de/main.json
cx-portal/src/assets/locales/de/servicerelease.json
cx-portal/src/assets/locales/en/main.json
cx-portal/src/assets/locales/en/servicerelease.json
cx-portal/src/components/shared/basic/ReleaseProcess/ValidateAndPublish/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/components/CommonValidateAndPublish.tsx

Removed 'data security information' and 'connected data' sections which are not relevant from validate and publish
ref:-CPLP-2473

BugFix. Removed page sections : App Release Process

---

CHANGELOG.md
cx-portal/src/components/shared/basic/ReleaseProcess/ReleaseProcessSteps.scss
cx-portal/src/components/shared/basic/ReleaseProcess/components/CommonValidateAndPublish.tsx

Download functionality added to 'documents' in 'validate and publish'
ref:-CPLP-2471

BugFix. document download : App Release Process

---

CHANGELOG.md
cx-portal/src/components/pages/Admin/components/RegistrationRequests/components/CheckList/index.tsx

Application checklist button width is set a constant value so that the layout size does not relay on cancel process button

BugFix(Checklist) - layout issue fix

---

CHANGELOG.md
cx-portal/src/components/shared/basic/ReleaseProcess/components/CommonValidateAndPublish.tsx

Added privacy policies to validate and publish in app release process
ref:-CPLP-1979

Privacy policies: App release process

---

CHANGELOG.md
cx-portal/src/components/pages/AppOverview/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/components/ConnectorFormInputFieldImage.tsx
cx-portal/src/features/appManagement/types.ts

fixed error message display for conformity document
Reset active step back to 1 in app overview page

conformity document and app overview

---

cx-portal/src/components/pages/ServiceMarketplaceDetail/components/MarketplaceDocuments/index.tsx
cx-portal/src/components/pages/ServiceReleaseProcess/components/ServiceDetails.tsx

Download document issue fix in service details page

Bug fix(Service Details) - Download document 

---

CHANGELOG.md
cx-portal-shared-components/src/components/content/Cards/CardDecision.tsx
cx-portal/src/assets/locales/de/servicerelease.json
cx-portal/src/assets/locales/en/servicerelease.json
cx-portal/src/components/pages/ServiceAdminBoard/index.tsx
cx-portal/src/components/shared/templates/AdminBoard/AdminBoard.scss
cx-portal/src/components/shared/templates/AdminBoard/AdminBoardElements.tsx
cx-portal/src/components/shared/templates/AdminBoard/index.tsx
cx-portal/src/components/shared/templates/Subscription/index.tsx
cx-portal/src/features/adminBoard/serviceAdminBoardApiSlice.ts
cx-portal/src/features/store.ts
cx-portal/src/types/Config.tsx

Service Admin Board enabled. App Admin Board & Service Admin Board to use common component. All features connected to the backend

Feature(Service admin board) - Admin board with filter, sort and search options

---

CHANGELOG.md
cx-portal/src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
cx-portal/src/types/Patterns.ts

Fixed provider name validation in app card
ref:-CPLP-2528

BugFix. provider name validation : App Release Process

---

cx-portal-shared-components/src/components/basic/ImageGallery/ImageItemOverlay.tsx
cx-portal/src/components/shared/templates/StaticTemplateResponsive/Cards/RenderImage.tsx
cx-portal/src/components/shared/templates/StaticTemplateResponsive/StaticTemplate.scss

Grey color at the bottom of the zoomed image & Spacing issue in TextAndImage component

BugFix(Static templates) - UI fixes

---

CHANGELOG.md
cx-portal/src/components/pages/AppDetail/index.tsx
cx-portal/src/components/shared/templates/AdminBoard/index.tsx

Navigate back to previous screen from App details screen
Show Loading component in admin board screen

BugFix - Navigation & Loading component

---

CHANGELOG.md
cx-portal/src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/components/CommonValidateAndPublish.tsx

Included role description in technical integration role creation
Ref: CPLP-2478

App roles : App Release Process

---

cx-portal-shared-components/src/components/content/Cards/index.tsx
cx-portal/src/components/pages/AppDetail/index.tsx

Removed explicit navigation from AppDetails page. Do navigate to previous page always

fix(navigation): remove explicit navigation

---

cx-portal/src/features/adminBoard/serviceAdminBoardApiSlice.ts

this change is wrt backend's path change for service management related feature

update(end point) : approve and decline end point updates

---

CHANGELOG.md
cx-portal/src/components/overlays/EditPortalRoles/index.tsx
cx-portal/src/components/shared/basic/UserRoles/index.tsx
cx-portal/src/components/shared/frame/UserList/index.tsx

CPLP-2544
Fixed UserDetail page broke issue if no roles exist

Fix: user detail load fix

---

CHANGELOG.md
cx-portal/src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/BetaTest/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/ContractAndConsent/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/OfferCard/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/OfferContractAndConsent/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/OfferPage/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/OfferValidateAndPublish/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/ValidateAndPublish/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/components/CommonContractAndConsent.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/components/CommonValidateAndPublish.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/components/SnackbarNotificationWithButtons.tsx

Enable help button for app release and service release process
Ref: CPLP-2551 and CPLP-2566

feature: enable help button    

---

CHANGELOG.md
cx-portal/src/features/admin/mapper.ts

TEST-837
Company data: wrong data after the street number

fix: companydata address null issue

---

CHANGELOG.md
cx-portal/src/assets/locales/de/main.json
cx-portal/src/assets/locales/de/servicerelease.json
cx-portal/src/assets/locales/en/main.json
cx-portal/src/assets/locales/en/servicerelease.json
cx-portal/src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/OfferCard/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/components/ComponentStyles.scss
cx-portal/src/components/shared/basic/ReleaseProcess/components/RetryOverlay.tsx

On open Pre-saved app/service fails to load the data, allow user to reload or to go back to the previous page.
Currently it is showing empty form inputs and user is not notified about the error.

feature(app/service release process) -  Error handle

---

CHANGELOG.md
cx-portal/src/components/shared/basic/ReleaseProcess/AppPage/index.tsx
cx-portal/src/features/appManagement/apiSlice.ts

After uploading the image/file inside the app release process, the user is not able to delete it again.
Only after clicking "SAVE & PROCEED" and coming back to the page, the user can delete the image, this is fixed.
Ref: TEST-866

fix(delete images) : App Release Process

---

CHANGELOG.md
cx-portal-shared-components/src/components/basic/StaticTable/HorizontalTable.tsx
cx-portal-shared-components/src/components/basic/StaticTable/VerticalTable.tsx

Added typography for static table to update headline sizing
Ref: CPLP-2537

update(static table) : Shared UI Components

---

cx-portal/src/components/shared/basic/ReleaseProcess/OfferPage/index.tsx

Added a PDF to the chapter "Supporting Material". Afterwards tried to replace it but not able to delete the file

bugfix(service release process): delete supporting file issue fix

---

CHANGELOG.md
cx-portal/src/components/shared/frame/Footer/index.tsx

Updated footer color similar to the app release process form
Ref: CPLP-2558

update(footer) : App Release Process

---

CHANGELOG.md
cx-portal-shared-components/src/components/basic/Table/PageLoadingTable.tsx
cx-portal-shared-components/src/components/basic/Table/components/Error/Error400Overlay.tsx
cx-portal-shared-components/src/components/basic/Table/components/Error/Error500Overlay.tsx
cx-portal-shared-components/src/components/basic/Table/index.tsx
cx-portal/src/assets/locales/de/main.json
cx-portal/src/assets/locales/en/main.json
cx-portal/src/components/pages/EdcConnector/edcConnectorTableColumns.tsx
cx-portal/src/components/pages/EdcConnector/edcManagedConnectorTableColumns.tsx
cx-portal/src/components/pages/EdcConnector/edcOwnConnectorTableColumns.tsx
cx-portal/src/components/pages/EdcConnector/index.tsx
cx-portal/src/features/connector/connectorApiSlice.ts

Show a table to list managed connectors. Handle error scenarios in the table component which is common across the portal app. Show appropriate error message from the server and display action item to user based on the status code

feature(connectors) - display managed connectors and show error scenrio

---

.github/workflows/release-release_candidate.yml
.github/workflows/release.yml
CHANGELOG.md
DEPENDENCIES
cx-portal-shared-components/package.json
cx-portal/package.json
package.json

release(1.4.0): merge main into dev

---

CHANGELOG.md
cx-portal-shared-components/src/components/basic/SortOption/index.tsx
cx-portal/src/components/pages/NotificationCenter/Notifications.scss
cx-portal/src/components/pages/NotificationCenter/index.tsx
cx-portal/src/components/pages/ServiceMarketplace/ServiceMarketplace.scss
cx-portal/src/components/pages/ServiceMarketplace/index.tsx
cx-portal/src/components/shared/frame/SortImage/index.tsx
cx-portal/src/components/shared/templates/AdminBoard/AdminBoard.scss
cx-portal/src/components/shared/templates/AdminBoard/index.tsx
cx-portal/src/components/shared/templates/Subscription/Subscription.scss
cx-portal/src/components/shared/templates/Subscription/index.tsx

moved sortIcon to a shared folder. reuse it all over the place. hover effects added to both modal and icon

updates(sort section) : sortIcon and modal update

---

CHANGELOG.md
cx-portal/src/components/shared/templates/StaticTemplateResponsive/Cards/FlexImages.tsx
cx-portal/src/components/shared/templates/StaticTemplateResponsive/Cards/GridImages.tsx
cx-portal/src/components/shared/templates/StaticTemplateResponsive/Cards/ImageTextSideBySide.tsx
cx-portal/src/components/shared/templates/StaticTemplateResponsive/StaticTemplate.scss
cx-portal/src/components/shared/templates/StaticTemplateResponsive/StaticTypes.ts
cx-portal/src/components/shared/templates/StaticTemplateResponsive/index.tsx

templates added to handle grid and flex fashioned images with Text which is aligned centre to the page

updates(static template) : two new templates added. 

---

cx-portal/src/components/pages/ServiceAdminBoardDetail/index.tsx

removed unwanted api query from admin details page.

updates(admin details) : removed unwanted api query

---

CHANGELOG.md
cx-portal-shared-components/src/components/basic/ImageGallery/ImageItem.tsx

Issue - background page is moving up and double headline is getting display

bugfix(image component) : do not hide image on hover/zoom-in action

---

cx-portal/src/components/shared/basic/ReleaseProcess/AppMarketCard/index.tsx
cx-portal/src/components/shared/basic/ReleaseProcess/TechnicalIntegration/index.tsx

Style update : App Release Process

---

cx-portal/src/assets/locales/de/notification.json
cx-portal/src/assets/locales/en/notification.json
cx-portal/src/components/pages/NotificationCenter/NotificationItem.tsx
cx-portal/src/components/pages/NotificationCenter/Notifications.scss

Style fix - allow description to occupy more space when action is not available.

updates(notification) : text updates and small style fix

---

cx-portal/src/components/overlays/UpdateCompanyRole/index.tsx

This PR related to CPLP-1532 in which having update to display data of changed roles only.

update(company role): change data into overlay as per selected roles

---

CHANGELOG.md
cx-portal/src/components/shared/templates/StaticTemplateResponsive/Cards/ImageTextCenterAligned.tsx
cx-portal/src/components/shared/templates/StaticTemplateResponsive/Cards/ImageTextSideBySide.tsx
cx-portal/src/components/shared/templates/StaticTemplateResponsive/Cards/ImageVideoWrapper.tsx
cx-portal/src/components/shared/templates/StaticTemplateResponsive/Cards/TextCenterAligned.tsx
cx-portal/src/components/shared/templates/StaticTemplateResponsive/Cards/TextCenterAlignedBody2.tsx
cx-portal/src/components/shared/templates/StaticTemplateResponsive/Cards/TextImageCenterAligned.tsx
cx-portal/src/components/shared/templates/StaticTemplateResponsive/Cards/TextImageSideBySide.tsx
cx-portal/src/components/shared/templates/StaticTemplateResponsive/Cards/TextVideoSideBySide.tsx
cx-portal/src/components/shared/templates/StaticTemplateResponsive/Cards/VideoTextSideBySide.tsx
cx-portal/src/components/shared/templates/StaticTemplateResponsive/StaticTemplate.scss
cx-portal/src/components/shared/templates/StaticTemplateResponsive/index.tsx

To support the users, add a "up" button in the single headline sections

feature(static templates) : provide arrow up icon on each section

---

CHANGELOG.md
cx-portal/src/components/pages/ServiceMarketplace/RecommendedServices.tsx
cx-portal/src/components/pages/ServiceMarketplace/ServicesElements.tsx
cx-portal/src/components/pages/ServiceMarketplaceDetail/components/MarketplaceHeader/index.tsx

images are missing in the list and details page

bugfix(service marketplace) : fetch images from asset repo
